
####################### PROJECT #######################
####################### PROJECT #######################  
####################### PROJECT #######################

name: RJPS_SwiftUI

options:
  bundleIdPrefix: com.rjps.swiftui
  xcodeVersion: '12.0.2'
  deploymentTarget: '13.0'
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'

####################### AUXILIAR FOLDERS #######################
####################### AUXILIAR FOLDERS #######################  
####################### AUXILIAR FOLDERS #######################

fileGroups:
  - ../Documents

####################### CONFIGS #######################
####################### CONFIGS #######################  
####################### CONFIGS #######################

configs:
  Debug_Dev: debug
  Debug_QA: debug
  Debug_Prod: debug
  Release: release
  Adhoc: release
  Beta: release
  
####################### SETTINGS #######################
####################### SETTINGS #######################  
####################### SETTINGS #######################

settings:
  base:
    ENABLE_BITCODE: NO
  configs:
    Release: 
      ENABLE_BITCODE: YES
     
targetTemplates:
  Framework:
    platform: iOS
    deploymentTarget: '13.0'
    type: framework
    #settings:
    #  FRAMEWORK_SEARCH_PATHS: $(inherited) $(SRCROOT)/Carthage/Build/iOS
 
####################### SPM #######################
####################### SPM #######################  
####################### SPM #######################

packages:
  RJSLibUF:
    url: https://github.com/ricardopsantos/RJSLibUF
#    from: 1.0.0
    revision: 8be04fcc539a457915f46c0f3af6582a2ab0b01b

####################### TARGETS #######################
####################### TARGETS #######################  
####################### TARGETS #######################
       
targets:
        
## Base App

  RJPS_SwiftUI:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
       - path: ../RJPS_SwiftUI
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: true
      - package: RJSLibUF
        product: RJSLibUFAppThemes
        link: true
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: true
        
      #- target: AppHourlyChallenge
      - target: AppRyanair
        link: true
      - target: AppWeather
        link: true
      #- target: DocumentsVisual
      #  link: true  

    #postCompileScripts:
    #  - script: |
    #            if which swiftlint >/dev/null; then
    #               swiftlint
    #            else
    #               echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    #            fi
    #    name: Run SwiftLint
        
######################### AppHourlyChallenge

#  AppHourlyChallenge:
#    templates: 
#      - Framework
#    sources: 
#      - path: ../AppHourlyChallenge
#    dependencies:
#      - target: UtilsStorage
#        link: false
#      - target: BaseDomain
#        link: false
#      - target: UtilsDesignables
#        link: false  

####################### AppRyanair ##

  AppRyanair:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanair  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFAppThemes
        link: false
      - target: AppRyanairCore
        link: false
      - target: AppRyanairDomain
        link: false
      - target: UtilsDesignables
        link: false  
      - target: BaseDomain
        link: false  
      
  AppRyanairDomain:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairDomain
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: false
      - target: BaseDomain
        link: false
        
  AppRyanairCore:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairCore  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - target: AppRyanairDomain
        link: false
      - target: AppRyanairWebAPI
        link: false  
      - target: Utils
        link: false
      - target: UtilsStorage
        link: false
      - target: BaseDomain
        link: false
        
  AppRyanairWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairWebAPI
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: false
      - target: AppRyanairDomain
        link: false 
      - target: UtilsNetworking
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false   
 
######################### AppWeather

  AppWeather:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeather  
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase       
        link: false
      - package: RJSLibUF
        product: RJSLibUFAppThemes
        link: false
      - target: AppWeatherDomain
        link: false  
      - target: BaseDomain
        link: false  
      - target: AppWeatherCore
        link: false     
      - target: UtilsDesignables
        link: false  
        
  AppWeatherDomain:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherDomain
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: true ############################################
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: false
      - target: BaseDomain
        link: false  
        
  AppWeatherCore:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherCore
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - target: AppWeatherDomain
        link: false
      - target: AppWeatherWebAPI
        link: false  
      - target: BaseDomain
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false 
        
  AppWeatherWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherWebAPI
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: false
      - target: AppWeatherDomain
        link: false 
      - target: UtilsNetworking
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false     
         
######################### Generic Utils
      
  DevTools:
    templates: 
      - Framework
    sources:
      - path: ../DevTools
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
        
  BaseDomain:
    templates: 
      - Framework
    sources:
      - path: ../BaseDomain
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
     
  PublicCode:
    templates: 
      - Framework
    sources:
      - path: ../PublicCode
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
        
  Utils:
    templates: 
      - Framework
    sources: 
      - path: ../Utils
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: true ############################################
        
  UtilsDesignables:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsDesignables
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        product: RJSLibUFAppThemes
        link: false
      - target: UtilsExtensions
        link: false
      - target: Utils
        link: false
        
  UtilsExtensions:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsExtensions   
#    dependencies:
#      - package: RJSLibUF
#        product: RJSLibUFBase
#        link: false
        
  UtilsNetworking:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsNetworking
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: false
      - target: UtilsExtensions
        link: false
      - target: UtilsStorage
        link: false
  
  UtilsStorage:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsStorage
    dependencies:
      - package: RJSLibUF
        product: RJSLibUFBase
        link: true ############################################
      - package: RJSLibUF
        product: RJSLibUFNetworking
        link: true ############################################
      - target: UtilsExtensions
        link: false
      - target: BaseDomain
        link: false
    
#  DocumentsVisual:
#    templates: 
#      - Framework
#    sources: 
#      - path: ../DocumentsVisual
#    dependencies:
#      - package: RJSLibUF
#        product: RJSLibUFBase
#        link: false
#        product: RJSLibUFAppThemes
#        link: false
#      - target: UtilsExtensions
#        link: false
#      - target: UtilsDesignables
#        link: false
#      - target: UtilsStorage
#        link: false
        
 
