
####################### PROJECT #######################
####################### PROJECT #######################  
####################### PROJECT #######################

name: RJPS_SwiftUI

options:
  bundleIdPrefix: com.rjps.swiftui
  xcodeVersion: '12.0.2'
  deploymentTarget: '13.0'
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: '2.18.0'

####################### AUXILIAR FOLDERS #######################
####################### AUXILIAR FOLDERS #######################  
####################### AUXILIAR FOLDERS #######################

fileGroups:
  - ../Documents

####################### CONFIGS #######################
####################### CONFIGS #######################  
####################### CONFIGS #######################

configs:
  Debug_Dev: debug
  Debug_QA: debug
  Debug_Prod: debug
  Release: release
  Adhoc: release
  Beta: release
  
####################### SETTINGS #######################
####################### SETTINGS #######################  
####################### SETTINGS #######################

settings:
  base:
    ENABLE_BITCODE: NO
  configs:
    Release: 
      ENABLE_BITCODE: YES
     
targetTemplates:
  Framework:
    platform: iOS
    deploymentTarget: '13.0'
    type: framework
    #settings:
    #  FRAMEWORK_SEARCH_PATHS: $(inherited) $(SRCROOT)/Carthage/Build/iOS
 

####################### TARGETS #######################
####################### TARGETS #######################  
####################### TARGETS #######################
       
targets:
        
## Base App

  RJPS_SwiftUI:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
       - path: ../RJPS_SwiftUI
    dependencies:
      #- target: AppHourlyChallenge
      #  link: true
      - target: AppRyanair
        link: true
      - target: AppWeather
        link: true
      - target: DocumentsVisual
        link: true  

######################### AppHourlyChallenge

#  AppHourlyChallenge:
#    templates: 
#      - Framework
#    sources: 
#      - path: ../AppHourlyChallenge
#    dependencies:
#      - target: UtilsStorage
#        link: false
#      - target: BaseDomain
#        link: false
#      - target: UtilsDesignables
#        link: false  

####################### AppRyanair ##

  AppRyanair:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanair  
    dependencies:
      - target: AppRyanairCore
        link: false
      - target: AppRyanairDomain
        link: false
      - target: UtilsDesignables
        link: false  
      - target: BaseDomain
        link: false  
      
  AppRyanairDomain:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairDomain
    dependencies:
      - target: BaseDomain
        link: false
        
  AppRyanairCore:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairCore  
    dependencies:
      - target: AppRyanairDomain
        link: false
      - target: AppRyanairWebAPI
        link: false  
      - target: Utils
        link: false
      - target: UtilsStorage
        link: false
      - target: BaseDomain
        link: false
        
  AppRyanairWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../AppRyanairWebAPI
    dependencies:
      - target: AppRyanairDomain
        link: false 
      - target: UtilsNetworking
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false   
 
######################### AppWeather

  AppWeather:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeather  
    dependencies:
      - target: AppWeatherDomain
        link: false  
      - target: BaseDomain
        link: false  
      - target: AppWeatherCore
        link: false     
      - target: UtilsDesignables
        link: false  
        
  AppWeatherDomain:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherDomain
    dependencies:
      - target: BaseDomain
        link: false  
        
  AppWeatherCore:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherCore
    dependencies:
      - target: AppWeatherDomain
        link: false
      - target: AppWeatherWebAPI
        link: false  
      - target: BaseDomain
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false 
        
  AppWeatherWebAPI:
    templates: 
      - Framework
    sources: 
      - path: ../AppWeatherWebAPI
    dependencies:
      - target: AppWeatherDomain
        link: false 
      - target: UtilsNetworking
        link: false
      - target: UtilsStorage
        link: false
      - target: DevTools
        link: false     
         
######################### Generic Utils
      
  DevTools:
    templates: 
      - Framework
    sources:
      - path: ../DevTools
  
  BaseDomain:
    templates: 
      - Framework
    sources:
      - path: ../BaseDomain
      
  PublicCode:
    templates: 
      - Framework
    sources:
      - path: ../PublicCode
      
  Utils:
    templates: 
      - Framework
    sources: 
      - path: ../Utils

  UtilsDesignables:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsDesignables
    dependencies:
      - target: UtilsExtensions
        link: false
      - target: Utils
        link: false
        
  UtilsExtensions:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsExtensions   
      
  UtilsNetworking:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsNetworking
    dependencies:
      - target: UtilsExtensions
        link: false
      - target: UtilsStorage
        link: false
  
  UtilsStorage:
    templates: 
      - Framework
    sources: 
      - path: ../UtilsStorage
    dependencies:
      - target: UtilsExtensions
        link: false
      - target: BaseDomain
        link: false
    
  DocumentsVisual:
    templates: 
      - Framework
    sources: 
      - path: ../DocumentsVisual
    dependencies:
      - target: UtilsExtensions
        link: false
      - target: UtilsDesignables
        link: false
      - target: UtilsStorage
        link: false
        
 
